<?xml version='1.0'?>
<ns2:test-suite xmlns:ns2='urn:model.allure.qatools.yandex.ru' start='1675855251542' stop='1675855251970'>
    <name>Api Test</name>
    <title>Api Test</title>
    <test-cases>
        <test-case start='1675855251543' status='failed' stop='1675855251969'>
            <name>returns the correct response</name>
            <title>returns the correct response</title>
            <labels>
                <label name='language' value='javascript'/>
                <label name='framework' value='wdio'/>
                <label name='thread' value='0-0'/>
            </labels>
            <parameters>
                <parameter kind='argument' name='browser' value='chrome-109.0.0.0'/>
            </parameters>
            <steps>
                <step start='1675855251852' status='passed' stop='1675855251967'>
                    <name>takeScreenshot</name>
                    <title>takeScreenshot</title>
                    <attachments>
                        <attachment title='Screenshot' source='3319929a-1967-4729-b362-8c1ece5d94d3-attachment.png' type='image/png' size='5373'/>
                    </attachments>
                    <steps/>
                </step>
            </steps>
            <attachments/>
            <failure>
                <message>the id and userID are the same as expected: expected { userId: 10, id: 99, …(2) } to have property 'userId' of '10', but got 10      
                      actual expected
                      
                      '10'
                      </message>
                <stack-trace>AssertionError: the id and userID are the same as expected: expected { userId: 10, id: 99, …(2) } to have property 'userId' of '10', but got 10
                    at Context.&lt;anonymous> (file:///C:/Users/Magda/qa_l2/m.latka/test/specs/test.spec.js:23:16)
                    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)</stack-trace>
            </failure>
        </test-case>
    </test-cases>
</ns2:test-suite>